# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a6f34f8e83b3695088e37d2b611b1935cc2bff195b03a782c7d77294c813276030e5774568bc5ba22f6585c178ddc3be1ce89ce92b36796816b04e6c5ea436c

test:
  secret_key_base: 48089dec09526defa99a88281dbd0e810f8dc088d5d8f1e5cad41bae1cf38d6aa29e548c9eb54b24f48d90b2fed878c254cce37ad82c860b1d590f669174aac3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
